"use client";
import { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { getSupabaseBrowser } from "@/lib/supabase/browser";
import type { Product } from "@/lib/products/types";
type Line = { product: Product; quantity: number };
type CartContextValue = { lines: Line[]; add: (product: Product, quantity?: number) => void; setQuantity: (id: string, quantity: number) => void; remove: (id: string) => void; clear: () => void; count: number; subtotal: number };
const CartContext = createContext<CartContextValue | null>(null);
export function CartProvider({ children }: { children: React.ReactNode }) {
  const [lines, setLines] = useState<Line[]>([]); const [ready,setReady]=useState(false); const [userId,setUserId]=useState<string|null>(null); const syncReady=useRef(false); const merging=useRef(false); const activeUserId=useRef<string|null>(null); const linesRef=useRef(lines); linesRef.current=lines;
  useEffect(() => { try { const saved = localStorage.getItem("naskam-cart"); if (saved) setLines(JSON.parse(saved) as Line[]); } catch { console.error("Could not restore the saved cart"); } finally { setReady(true); } }, []);
  useEffect(() => { if(!ready)return;try { localStorage.setItem("naskam-cart", JSON.stringify(lines)); } catch { console.error("Could not save the cart"); } }, [lines,ready]);
  useEffect(()=>{if(!ready)return;const supabase=getSupabaseBrowser();if(!supabase)return;let active=true;const merge=async(nextUserId:string)=>{if(!active||syncReady.current||merging.current)return;merging.current=true;activeUserId.current=nextUserId;setUserId(nextUserId);try{const response=await fetch("/api/cart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:linesRef.current.map(line=>({productId:line.product.id,quantity:line.quantity}))})});if(!response.ok)throw new Error("Cart merge request failed");const result=await response.json() as {items:Line[]};if(!active||activeUserId.current!==nextUserId)return;setLines(result.items);syncReady.current=true;}catch(error){console.error("Signed-in cart could not be merged:",error);}finally{merging.current=false;}};void supabase.auth.getSession().then(({data})=>{if(data.session?.user)void merge(data.session.user.id);});const{data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(session?.user){activeUserId.current=session.user.id;void merge(session.user.id);}else{activeUserId.current=null;setUserId(null);syncReady.current=false;merging.current=false;if(event==="SIGNED_OUT"){setLines([]);try{localStorage.removeItem("naskam-cart");}catch(error){console.error("Could not clear the signed-out cart:",error);}}}});return()=>{active=false;subscription.unsubscribe();};},[ready]);
  useEffect(()=>{if(!ready||!userId||!syncReady.current)return;const timeout=setTimeout(()=>{void fetch("/api/cart",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:lines.map(line=>({productId:line.product.id,quantity:line.quantity}))})}).then(response=>{if(!response.ok)throw new Error("Cart sync failed");}).catch(error=>console.error("Signed-in cart could not be saved:",error));},300);return()=>clearTimeout(timeout);},[lines,ready,userId]);
  const value = useMemo<CartContextValue>(() => ({ lines, add: (product, quantity = 1) => setLines((current) => { const found = current.find((line) => line.product.id === product.id); return found ? current.map((line) => line.product.id === product.id ? { ...line, quantity: Math.min(line.quantity + quantity, product.stock_quantity) } : line) : [...current, { product, quantity: Math.min(quantity, product.stock_quantity) }]; }), setQuantity: (id, quantity) => setLines((current) => quantity < 1 ? current.filter((line) => line.product.id !== id) : current.map((line) => line.product.id === id ? { ...line, quantity: Math.min(quantity, line.product.stock_quantity) } : line)), remove: (id) => setLines((current) => current.filter((line) => line.product.id !== id)), clear: () => setLines([]), count: lines.reduce((sum, line) => sum + line.quantity, 0), subtotal: lines.reduce((sum, line) => sum + line.product.price * line.quantity, 0) }), [lines]);
  return <CartContext.Provider value={value}>{children}</CartContext.Provider>;
}
export function useCart() { const context = useContext(CartContext); if (!context) throw new Error("useCart must be used within CartProvider"); return context; }
