"use client";
import Link from "next/link";
import { ShoppingBag, Menu, X, Phone, UserRound } from "lucide-react";
import { useState } from "react";
import { useCart } from "./cart-provider";
export function SiteHeader() {
  const { count } = useCart(); const [open, setOpen] = useState(false);
  const links = [{ href: "/shop", text: "Shop" }, { href: "/#why-naskam", text: "Why NASKAM" }, { href: "/#contact", text: "Contact" }];
  return <><div className="bg-navy text-white"><div className="container flex h-9 items-center justify-between text-xs"><span>Reliable power for homes & businesses across Nigeria</span><a className="hidden items-center gap-2 sm:flex" href="mailto:sabrecall@gmail.com"><Phone size={13}/> Talk to our team</a></div></div><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="container flex h-[74px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="NASKAM home"><span className="grid h-11 w-11 place-items-center rounded-full border-[3px] border-red text-xl font-black text-navy">N</span><span className="leading-tight"><strong className="block text-[19px] font-black tracking-tight text-navy">NASKAM</strong><small className="text-[10px] font-bold tracking-[.13em] text-slate-600">COMMERCIAL ENTERPRISES</small></span></Link><nav className="hidden items-center gap-9 md:flex">{links.map((item) => <Link key={item.href} className="text-sm font-semibold text-slate-700 hover:text-red" href={item.href}>{item.text}</Link>)}</nav><div className="flex items-center gap-2"><Link aria-label="My account" className="grid h-11 w-11 place-items-center rounded-md border border-slate-200 text-navy hover:bg-slate-50" href="/account"><UserRound size={18}/></Link><Link className="relative flex h-11 items-center gap-2 rounded-md border border-slate-200 px-3 text-sm font-bold text-navy hover:bg-slate-50" href="/cart"><ShoppingBag size={18}/><span className="hidden sm:inline">Cart</span><span className="grid min-w-5 place-items-center rounded-full bg-red px-1 text-[11px] text-white">{count}</span></Link><button onClick={() => setOpen(!open)} className="grid h-11 w-11 place-items-center rounded-md border md:hidden" aria-label={open ? "Close menu" : "Open menu"}>{open ? <X/> : <Menu/>}</button></div></div>{open && <nav className="border-t bg-white p-4 md:hidden">{links.map((item) => <Link onClick={() => setOpen(false)} key={item.href} className="block rounded px-3 py-3 font-semibold text-slate-800 hover:bg-slate-50" href={item.href}>{item.text}</Link>)}<Link onClick={()=>setOpen(false)} className="block rounded px-3 py-3 font-semibold text-slate-800 hover:bg-slate-50" href="/account">My account</Link></nav>}</header></>;
}
